name: "VocaloidWikiPage"
on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-2022

    steps:
      # 检出代码
      - name: CheckOut Code
        uses: actions/checkout@v4
      # 安装 Python
      - name: setup python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      # 安装 PDM
      - name: "Prapare Libraries"
        run: python -m pip install pdm
      # 安装依赖
      - name: "Install"
        run: python -m pdm install
      
      - name: "Query Wiki Data"
        run: python -m pdm run get_api_data.py
      
      - name: "Image Convert"
        run: python -m pdm run image.py --input-dir=./images --output-dir=./image.out

      - name: "Stop Service"
        run: python -m pdm run api.py stop vocaloid-wp-service

      - name: "Apply to API"
        run: python -m pdm run api.py --file=./resolved,./image.out --api=${{ secrets.API_APPLY }} --token=${{ secrets.API_TOKEN }}
      
      - name: "Start Service"
        run: python -m pdm run api.py start vocaloid-wp-service
        